<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "Lassie-shop");
$APPLICATION->SetTitle("Lassie-shop");
?><?$APPLICATION->IncludeComponent(
    "bitrix:sale.bestsellers",
    "sale",
    Array(
        "ACTION_VARIABLE" => "action",
        "ADDITIONAL_PICT_PROP_2" => "MORE_PHOTO",
        "ADDITIONAL_PICT_PROP_3" => "MORE_PHOTO",
        "ADD_PROPERTIES_TO_BASKET" => "Y",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "BASKET_URL" => "/personal/cart/",
        "BY" => "QUANTITY",
        "CACHE_TIME" => "86400",
        "CACHE_TYPE" => "A",
        "CART_PROPERTIES_2" => array("BRAND_REF",""),
        "CART_PROPERTIES_3" => array("","SIZES_SHOES","SIZES_CLOTHES",""),
        "CONVERT_CURRENCY" => "N",
        "DETAIL_URL" => "",
        "FILTER" => array("CANCELED","ALLOW_DELIVERY","PAYED","DEDUCTED","N","P","F"),
        "HIDE_NOT_AVAILABLE" => "N",
        "LABEL_PROP_2" => "-",
        "LINE_ELEMENT_COUNT" => "5",
        "MESS_BTN_BUY" => "Купить",
        "MESS_BTN_DETAIL" => "Подробнее",
        "MESS_BTN_SUBSCRIBE" => "Подписаться",
        "MESS_NOT_AVAILABLE" => "Нет в наличии",
        "OFFER_TREE_PROPS_3" => array("COLOR_REF"),
        "PAGE_ELEMENT_COUNT" => "10",
        "PARTIAL_PRODUCT_PROPERTIES" => "Y",
        "PERIOD" => "100",
        "PRICE_CODE" => array("BASE"),
        "PRICE_VAT_INCLUDE" => "Y",
        "PRODUCT_ID_VARIABLE" => "id",
        "PRODUCT_PROPS_VARIABLE" => "prop",
        "PRODUCT_QUANTITY_VARIABLE" => "quantity",
        "PRODUCT_SUBSCRIPTION" => "N",
        "PROPERTY_CODE_2" => array("NEWPRODUCT","SALELEADER","SPECIALOFFER",""),
        "PROPERTY_CODE_3" => array("SIZES_SHOES","SIZES_CLOTHES",""),
        "SHOW_DISCOUNT_PERCENT" => "N",
        "SHOW_IMAGE" => "Y",
        "SHOW_NAME" => "Y",
        "SHOW_OLD_PRICE" => "N",
        "SHOW_PRICE_COUNT" => "1",
        "SHOW_PRODUCTS_2" => "Y",
        "TEMPLATE_THEME" => "blue",
        "USE_PRODUCT_QUANTITY" => "N"
    )
);?>
<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>